D3-API-by-ZTn/Application.Web/Controllers/HeroesController.cs
using Application.Web.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Application.Models.Heroes;

namespace Application.Web.Controllers
{
    public class HeroesController : BaseController
    {
        // GET: Heroes
        public ActionResult Index()
        {
            return View();
        }
        
        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroes([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x =>x.Hardcore != true)
                .Select(x => new HeroViewModel
            {
                ID = x.ID,
                BattleTag = x.ApplicationUser.BattleTag,
                Damage = x.Stats.Damage,
                Healing = x.Stats.Healing,
                HeroClass = x.HeroClass,
                IsHardcore = x.Hardcore,
                Life = x.Stats.Life,
                Name = x.Name,
                ParagonLevel = x.ParagonLevel,
                Toughness = x.Stats.Toughness

            });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesHardcore([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x =>x.ParagonLevel)
                .Where(x => x.Hardcore == true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesBarbarian([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.Barbarian && x.Hardcore != true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesBarbarianHardcore([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.Barbarian && x.Hardcore == true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesWizard([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.Wizard && x.Hardcore != true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesWizardHardcore([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.Wizard && x.Hardcore == true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesDemonHunter([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.DemonHunter && x.Hardcore != true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesDemonHunterHardcore([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.DemonHunter && x.Hardcore == true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesMonk([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.Monk && x.Hardcore != true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        //[OutputCache(Duration = 60 * 60)]
        public JsonResult ReadAllHeroesMonkHardcore([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Heroes.All()
                .OrderBy(x => x.ParagonLevel)
                .Where(x => x.HeroClass == HeroClass.Monk && x.Hardcore == true)
                .Select(x => new HeroViewModel
                {
                    ID = x.ID,
                    BattleTag = x.ApplicationUser.BattleTag,
                    Damage = x.Stats.Damage,
                    Healing = x.Stats.Healing,
                    HeroClass = x.HeroClass,
                    IsHardcore = x.Hardcore,
                    Life = x.Stats.Life,
                    Name = x.Name,
                    ParagonLevel = x.ParagonLevel,
                    Toughness = x.Stats.Toughness

                });

D3-API-by-ZTn/Application.Web/Views/Heroes/Details.cshtml
@model Application.Models.Heroes.Hero

<h2>@Model.Name [<small style="color:lightcoral"><a href="/Players/Details/@Model.CareerId">@Model.ApplicationUser.BattleTag</a></small>]</h2>
<hr />
<div class="row" style="margin-top: -10px;">
    <div class="col-md-3">
        <div class="panel panel-primary" style="width:200px;">
            <div class="panel-heading">
                <h3 class="panel-title">
                    @Model.Name [<small style="color:lightgray">@Model.ParagonLevel</small>]
                </h3>
            </div>
            <div class="panel-body">
                @switch (@Model.HeroClass)
                {
                    case Application.Models.Heroes.HeroClass.Unknown:
                        break;
                    case Application.Models.Heroes.HeroClass.Barbarian:
                        <img src="~/Content/img/barbarian-big.jpg" alt="Alternate Text" />
                        break;
                    case Application.Models.Heroes.HeroClass.Crusader:
                    <img src="~/Content/img/crusader-big.jpg" alt="Alternate Text" />
                        break;
                    case Application.Models.Heroes.HeroClass.DemonHunter:
                    <img src="~/Content/img/demon-hunter-big-female.jpg" alt="Alternate Text" />
                        break;
                    case Application.Models.Heroes.HeroClass.Monk:
                    <img src="~/Content/img/monk-big.jpg" alt="Alternate Text" />
                        break;
                    case Application.Models.Heroes.HeroClass.WitchDoctor:
                    <img src="~/Content/img/witch-doctor-big.jpg" alt="Alternate Text" />
                        break;
                    case Application.Models.Heroes.HeroClass.Wizard:
                    <img src="~/Content/img/wizard-big-female.jpg" alt="Alternate Text" />
                        break;
                    default:
                        break;
                }
                <br />
                <br />
                Damage: <span class="label label-warning pull-right">@Model.Stats.Damage</span><br />
                Life: <span class="label label-danger pull-right">@Model.Stats.Life</span><br />
                Healing: <span class="label label-success pull-right">@Model.Stats.Healing</span><br />
                Toughness: <span class="label label-success pull-right">@Model.Stats.Toughness</span><br />
            </div>
        </div>
        
        <table style="width: 100%;">
            <tr>
                <td>Likes: <span id="hero-votes">@Model.Votes.Count()</span></td>
                
                <td>@if (User.Identity.IsAuthenticated && @ViewBag.CanVote)
                {
                    @Ajax.ActionLink("Like", "Vote", new { id = Model.ID }, new AjaxOptions
                   {
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "hero-votes",
                       HttpMethod = "Post",
                       OnSuccess = "hideVoteButton"
                   }, new { @id = "vote-button", @class = "btn-sm btn-primary", @style="margin-left: 10px;" })
                }</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>Comments: @Model.Comments.Count()</td>
                <td><a href="#" class="btn-sm btn-primary" style="margin-left: 10px;">Comment</a></td>
            </tr>
        </table>

    </div>
    <div class="col-md-3" style="margin-left: -60px;">
        <h4>Additional Statistics:</h4>
        <h5 style="border-bottom: 1px solid gray; padding-bottom: 10px;color:lightcoral">Primary</h5>
        Strenght:
        <span class="label label-success pull-right">@Model.Stats.Strength</span>
        <br />
        Dexterity:
        <span class="label label-success pull-right">@Model.Stats.Dexterity</span>
        <br />
        Intelligence:
        <span class="label label-success pull-right">@Model.Stats.Intelligence</span>
        <br />
        Vitality:
        <span class="label label-success pull-right">@Model.Stats.Vitality</span>
        <br />
        <h5 style="border-bottom: 1px solid gray; padding-bottom: 10px;color:lightcoral">Damage</h5>
        Attack Speed:
        <span class="label label-danger pull-right">@Model.Stats.AttackSpeed</span>
        <br />
        Critical Chance:
        <span class="label label-danger pull-right">@Model.Stats.CritChance</span>
        <br />
        Critical Damage:
        <span class="label label-danger pull-right">@Model.Stats.CritDamage</span>
        <br />
        <h5 style="border-bottom: 1px solid gray; padding-bottom: 10px;color:lightcoral">Defence</h5>
        Armor:
        <span class="label label-warning pull-right">@Model.Stats.Armor</span>
        <br />
        Cold Resist:
        <span class="label label-warning pull-right">@Model.Stats.ColdResist</span>
        <br />
        Fire Resist:
        <span class="label label-warning pull-right">@Model.Stats.FireResist</span>
        <br />
        Lightning Resist:
        <span class="label label-warning pull-right">@Model.Stats.LightningResist</span>
        <br />
        Poison Resist:
        <span class="label label-warning pull-right">@Model.Stats.PoisonResist</span>
        <br />
        Arcane Resist:
        <span class="label label-warning pull-right">@Model.Stats.ArcaneResist</span>
        <br />
    </div>
    <div class="col-md-6">
        <h4>Hero Skills: </h4>
        <h5 style="border-bottom: 1px solid gray; padding-bottom: 10px;color:lightcoral">Active Skills</h5>
        @foreach (var skill in @Model.ActiveSkills)
        {
            switch (@Model.HeroClass)
            {
                case Application.Models.Heroes.HeroClass.Unknown:
                    break;
                case Application.Models.Heroes.HeroClass.Barbarian:
                    <a href="http://eu.battle.net/d3/en/class/barbarian/active/@(skill.Slug)" style="float: left; margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.Crusader:
                <a href="http://eu.battle.net/d3/en/class/crusader/active/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.DemonHunter:
                <a href="http://eu.battle.net/d3/en/class/demon-hunter/active/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.Monk:
                <a href="http://eu.battle.net/d3/en/class/monk/active/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.WitchDoctor:
                <a href="http://eu.battle.net/d3/en/class/witch-doctor/active/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.Wizard:
                <a href="http://eu.battle.net/d3/en/class/wizard/active/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                default:
                    break;
            }
        }
        <br />
        <div style="clear:both;"></div>
        <h5 style="border-bottom: 1px solid gray; padding-bottom: 10px;color:lightcoral">Passive Skills</h5>
        @foreach (var skill in @Model.PassiveSkills)
        {
            switch (@Model.HeroClass)
            {
                case Application.Models.Heroes.HeroClass.Unknown:
                    break;
                case Application.Models.Heroes.HeroClass.Barbarian:
                    <a href="http://eu.battle.net/d3/en/class/barbarian/passive/@(skill.Slug)" style="float: left; margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.Crusader:
                <a href="http://eu.battle.net/d3/en/class/crusader/passive/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.DemonHunter:
                <a href="http://eu.battle.net/d3/en/class/demon-hunter/passive/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.Monk:
                <a href="http://eu.battle.net/d3/en/class/monk/passive/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.WitchDoctor:
                <a href="http://eu.battle.net/d3/en/class/witch-doctor/passive/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                case Application.Models.Heroes.HeroClass.Wizard:
                <a href="http://eu.battle.net/d3/en/class/wizard/passive/@(skill.Slug)" style="float: left;margin-right: 10px;"><img src="http://media.blizzard.com/d3/icons/skills/64/@(skill.Icon).png" /></a>
                    break;
                default:
                    break;
            }
        }

        <div style="clear:both;"></div>
        <h5 style="border-bottom: 1px solid gray; padding-bottom: 10px;color:lightcoral">Items</h5>
        <button class="btn btn-primary center-block" style="margin-top: 30px;">Load Items</button>  
    </div>
</div>
<hr />
<div class="row" style="margin-top: -20px;">
    <div class="col-md-6" id="CommentsBox">
        @if (Model.Comments.Count() <= 0)
        {
            <p class="text-danger">No comments for this hero</p>
        }
        else
        {
            <h3>Comments:</h3>
            foreach (var comment in Model.Comments)
            {
                @Html.Partial("_CommentPartial", comment)
            }
        }
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        @if (User.Identity.IsAuthenticated)
        {

            using (Ajax.BeginForm("PostComment", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter, UpdateTargetId = "CommentsBox", OnFailure = "commentPostFailure" }))
            {
                <div class="panel" style="padding: 20px;">
                    @Html.Hidden("HeroId", Model.ID)
                    @Html.TextArea("comment", new { @class = "form-control", @placeholder = "Say something cool about this hero ..." })
                    @Html.AntiForgeryToken()
                    <input type="submit" class="btn btn-primary" value="Submit comment" style="margin-top:10px;" />
                </div>
            }
        }
    </div>
</div>


@section scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function commentPostFailure() {
            alert("Empty comments are not allowed");
        }

        function hideVoteButton() {
            $("#vote-button").hide();
        }
    </script>
}

<script src="http://us.battle.net/d3/static/js/tooltips.js"></script>

D3-API-by-ZTn/Application.Web/Views/Heroes/Index.cshtml
<h2>Best Heroes</h2>

@(Html.Kendo()
.Grid<Application.Web.Models.HeroViewModel>()
.Name("heroes-grid")
.Pageable()
.Sortable()
.Columns(col =>
{
    col.Bound(m => m.Name).ClientTemplate(
    "<a href='" + Url.Action("Details", "Heroes") + "/#= ID #'" + ">#= Name #</a>");
    col.Bound(m => m.BattleTag);
    col.Bound(m => m.Damage);
    col.Bound(m => m.Life);
    col.Bound(m => m.Toughness);
    col.Bound(m => m.Healing);
    col.Bound(m => m.HeroClass);
    col.Bound(m => m.ParagonLevel);
})
            .DataSource(data =>
            {
                data.Ajax()
                    .ServerOperation(true)
                    .Read("ReadAllHeroes", "Heroes")
                    .PageSize(10)
                    .Sort(sort =>
                    {
                        sort.Add(hero => hero.ParagonLevel).Descending();
                        sort.Add(hero => hero.Damage);
                        sort.Add(hero => hero.Toughness);
                    });
            }))