D3-API-by-ZTn/Application.Web/Controllers/HeroCommentsController.cs
using Application.Web.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Application.Web.Controllers
{
    public class HeroCommentsController : BaseController
    {
        // GET: HeroComments
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ReadAllComments([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.HeroComments.All().Select(x => new CommentViewModel
            {
                Id = x.ID,
                Content = x.Content,
                AuthorUserName = x.Author.UserName,
                HeroName = x.Hero.Name,
                HeroId = x.HeroId
            });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }


        public JsonResult UpdateComment([DataSourceRequest] DataSourceRequest request, CommentViewModel comment)
        {
            var commentDb = this.Data.HeroComments.Find(comment.Id);

            commentDb.Content = comment.Content;
            this.Data.SaveChanges();

            return Json(new[] { comment }.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult DestroyComment([DataSourceRequest] DataSourceRequest request, CommentViewModel comment)
        {
            this.Data.HeroComments.Delete(comment.Id);
            this.Data.SaveChanges();
            return Json(new[] { comment }.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }


    }
}

D3-API-by-ZTn/Application.Web/Views/Shared/_CommentPartial.cshtml
@model Application.Models.Heroes.HeroComment
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Commented by: @Model.Author.UserName</h3>
    </div>
    <div class="panel-body">
        @Model.Content
    </div>
</div>

D3-API-by-ZTn/Application.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/custom")
    @Styles.Render("~/Content/kendo")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Diablo III Ladders", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Players", "Index", "Players")</li>
                    <li>@Html.ActionLink("Heroes", "Index", "Heroes")</li>
                    <li>@Html.ActionLink("Guides", "Index", "Guides")</li>
                    @*<li>@Html.ActionLink("Classes", "Index", "Classes")</li>*@
                    <li>@Html.ActionLink("About", "Index", "About")</li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Admin <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Heroes</a></li>
                                <li>@Html.ActionLink("Hero Comments", "Index", "HeroComments")</li>
                                <li><a href="#">Guides</a></li>
                                <li><a href="#">Guides Comments</a></li>
                            </ul>
                        </li>
                    }
                    </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Diablo III Ladders by nzhul</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")
    @RenderSection("scripts", required: false)
</body>
</html>