D3-API-by-ZTn/Application.Web/Controllers/PlayersController.cs
using Application.Web.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Application.Web.Controllers
{
    public class PlayersController : BaseController
    {
        // GET: Players
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ReadAllCareers([DataSourceRequest] DataSourceRequest request)
        {
            var result = this.Data.Careers.All().Select(x => new CareerSummaryViewModel
            {
                Id = x.ID,
                BattleTag = x.BattleTag,
                EliteMonsterKills = x.Kills.elites,
                HardcoreMonsterKills = x.Kills.hardcoreMonsters,
                MonsterKills = x.Kills.monsters,
                ParagonLevel = x.ParagonLevel,
                ParagonLevelSeason = x.ParagonLevelSeason,
                ParagonLevelSeasonHardcore = x.ParagonLevelSeasonHardcore,
                PostCount = x.ApplicationUser.PostsCount,
                UserName = x.ApplicationUser.UserName,
                Heroes = x.Heroes.Select(h => new HeroViewModel 
                    { 
                        ID = h.ID,
                        HeroClass = h.HeroClass,
                        Name = h.Name
                    })
            });

            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int id)
        {
            var userId = this.User.Identity.GetUserId();

            var viewModel = this.Data.Careers.All()
                .Where(x => x.ID == id)
                .Select(x => new CareerDetailsViewModel
                {
                    ApplicationUser = x.ApplicationUser,
                    BattleTag = x.BattleTag,
                    Heroes = x.Heroes
                        .OrderByDescending(h => h.Stats.Damage)
                        .ThenByDescending(h => h.Stats.Toughness)
                        .Select(h => new HeroViewModel
                        {
                            ID = h.ID,
                            HeroClass = h.HeroClass,
                            Name = h.Name,
                            Damage = h.Stats.Damage,
                            Toughness = h.Stats.Toughness,
                            Life = h.Stats.Life,
                            Healing = h.Stats.Healing,
                            IsHardcore = h.Hardcore
                        }),
                    Kills = x.Kills,
                    ParagonLevel = x.ParagonLevel,
                    ParagonLevelHardcore = x.ParagonLevelHardcore,
                    ParagonLevelSeason = x.ParagonLevelSeason,
                    ParagonLevelSeasonHardcore = x.ParagonLevelSeason,
                    Progression = x.Progression,
                    TimePlayed = x.TimePlayed
                }).FirstOrDefault();

            return View(viewModel);
        }
    }
}

D3-API-by-ZTn/Application.Web/Views/Players/Details.cshtml
@model Application.Web.Models.CareerDetailsViewModel

@{
    ViewBag.Title = "View";
}

<h2>@Model.ApplicationUser.UserName [<small style="color:lightcoral">@Model.BattleTag</small>]</h2>
<hr />
<div class="row">
    <div class="col-md-5">
        <table>
            <tr>
                <td><img src="http://www.d3bg.org/img/forum/avatars/avatar_t3_4.jpg" alt="Avatar Image" style="border: 1px solid black;" /></td>
                <td style="padding: 10px;"><h4>About me:</h4>
                    <p>Simple description Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                </td>
            </tr>
            <tr>
                <td>Comments: @Model.ApplicationUser.PostsCount</td>
                <td><img src="~/Content/img/monster-kills.png" alt="Monster KIlls" /> Monster Kills: @Model.Kills.monsters</td>
            </tr>
            <tr>
                <td></td>
                <td><img src="~/Content/img/monster-kills-elite.png" alt="Monster KIlls" /> Elite Kills: @Model.Kills.elites</td>
            </tr>
            <tr>
                <td></td>
                <td><img src="~/Content/img/monster-kills-hardcore.png" alt="Monster KIlls" /> Hardcore Kills: @Model.Kills.hardcoreMonsters</td>
            </tr>
        </table>
        
    </div>
    <div class="col-md-6">
        <h4 style="margin-left: 40px;">Time Played by Class:</h4>
        <table>
            <tr>
                <td><img style="margin: 12px 10px 0px;" src="~/Content/img/barbarian_male.png" title="Barbarian" alt="Alternate Text" /></td>
                <td><div class="progressbar barbarian-progress"><div></div></div></td>
            </tr>
            <tr>
                <td><img style="margin: 12px 10px 0px;" src="~/Content/img/monk_male.png" title="Monk" alt="Alternate Text" /></td>
                <td><div class="progressbar monk-progress"><div></div></div></td>
            </tr>
            <tr>
                <td><img style="margin: 12px 10px 0px;" src="~/Content/img/wizard_female.png" title="Wizard" alt="Alternate Text" /></td>
                <td><div class="progressbar wizard-progress"><div></div></div></td>
            </tr>
            <tr>
                <td><img style="margin: 12px 10px 0px;" src="~/Content/img/witchdoctor_male.png" title="Witch Doctor" alt="Alternate Text" /></td>
                <td><div class="progressbar witch-doctor-progress"><div></div></div></td>
            </tr>
            <tr>
                <td><img style="margin: 12px 10px 0px;" src="~/Content/img/crusader_male.png" title="Crusader" alt="Alternate Text" /></td>
                <td><div class="progressbar crusader-progress"><div></div></div></td>
            </tr>
            <tr>
                <td><img style="margin: 12px 10px 0px;" src="~/Content/img/demonhunter_female.png" title="Demon Hunter" alt="Alternate Text" /></td>
                <td><div class="progressbar demon-hunter-progress"><div></div></div></td>
            </tr>
        </table>
        
    </div>
    
</div>
<hr />
<div class="row">

    <h3 style="margin-left:20px;margin-top:-10px;margin-bottom:20px;">@Model.ApplicationUser.UserName Heroes:</h3>
    @for (int i = 0; i < Model.Heroes.Count(); i++)
    {
        var hero = Model.Heroes.ElementAt(i);
        <div class="col-sm-2" style="margin-right:35px;">
            <div class="panel panel-primary" style="width:200px;">
                <div class="panel-heading">
                    <h3 class="panel-title"><a href="/Heroes/Details/@hero.ID">@hero.Name</a>  @if (@hero.IsHardcore)
                    { <span class="label label-danger pull-right">[HC]</span><br /> }</h3>
                </div>
                <div class="panel-body">
                    @switch (@hero.HeroClass)
                    {
                        case Application.Models.Heroes.HeroClass.Unknown:
                            break;
                        case Application.Models.Heroes.HeroClass.Barbarian:
                            <img src="~/Content/img/barbarian-big.jpg" alt="Alternate Text" />
                            break;
                        case Application.Models.Heroes.HeroClass.Crusader:
                        <img src="~/Content/img/crusader-big.jpg" alt="Alternate Text" />
                            break;
                        case Application.Models.Heroes.HeroClass.DemonHunter:
                        <img src="~/Content/img/demon-hunter-big-female.jpg" alt="Alternate Text" />
                            break;
                        case Application.Models.Heroes.HeroClass.Monk:
                        <img src="~/Content/img/monk-big.jpg" alt="Alternate Text" />
                            break;
                        case Application.Models.Heroes.HeroClass.WitchDoctor:
                        <img src="~/Content/img/witch-doctor-big.jpg" alt="Alternate Text" />
                            break;
                        case Application.Models.Heroes.HeroClass.Wizard:
                        <img src="~/Content/img/wizard-big-female.jpg" alt="Alternate Text" />
                            break;
                        default:
                            break;
                    }
                    <br />
                    <br />
                    Damage: <span class="label label-warning pull-right">@hero.Damage</span><br />
                    Life: <span class="label label-danger pull-right">@hero.Life</span><br />
                    Healing: <span class="label label-success pull-right">@hero.Healing</span><br />
                    Toughness: <span class="label label-success pull-right">@hero.Toughness</span><br />


                </div>
            </div>
        </div>
        if (i > 0 && (i + 1) % 5 == 0)
        {
            @:</div>
            @:<div class="row">
    }
    }
</div>



<script>
    (function ($) {

        $.fn.progress = function (options) {
            switch (typeof options) {
                case "number":
                    options = { amount: options };
                    break;
                case "string":
                    options = { color: options };
                    break;
            }

            // This is the easiest way to have default options.
            var defaults = {
                amount: 100,
                color: 'rgb(180, 157, 123'
            };

            var options = $.extend({}, defaults, options);

            //firstly, make me a progressbar
            this.css({ 'width': 'auto', 'height': '25px', 'border': '1px solid black', 'background-color': 'black' });

            //find the div to extend
            var div = this.find("div");
            console.debug('div', div);
            console.debug('progress', (options.amount * 5) + 'px');
            div.css({ 'backgroundColor': options.color, 'width': '0px', 'height': '25px' }).animate({ 'width': (options.amount * 5) + 'px' });

            return this;

        };

    }(jQuery));
</script>
<script>
    $('.barbarian-progress').progress(@Model.TimePlayed.Barbarian * 100);
    $('.monk-progress').progress(@Model.TimePlayed.Monk * 100);
    $('.wizard-progress').progress(@Model.TimePlayed.Wizard * 100);
    $('.witch-doctor-progress').progress(@Model.TimePlayed.WitchDoctor * 100);
    $('.crusader-progress').progress(@Model.TimePlayed.Crusader * 100);
    $('.demon-hunter-progress').progress(@Model.TimePlayed.DemonHunter * 100);
</script>

D3-API-by-ZTn/Application.Web/Views/Players/Index.cshtml
<h2>Best Players</h2>

@(Html.Kendo()
.Grid<Application.Web.Models.CareerSummaryViewModel>()
.Name("career-grid")
.Pageable()
.Sortable()
.Columns(col =>
{
    col.Bound(m => m.UserName).ClientTemplate(
    "<a href='" + Url.Action("Details", "Players") + "/#= Id #'" + ">#= UserName #</a>");
    col.Bound(m => m.BattleTag);
    col.Bound(m => m.PostCount);
    col.Bound(m => m.MonsterKills);
    col.Bound(m => m.EliteMonsterKills);
    col.Bound(m => m.HardcoreMonsterKills);
    col.Bound(m => m.ParagonLevel);
    col.Bound(m => m.ParagonLevelSeason);
    col.Bound(m => m.ParagonLevelSeasonHardcore);
})
            .DataSource(data =>
            {
                data.Ajax()
                    .ServerOperation(true)
                    .Read("ReadAllCareers", "Players")
                    .PageSize(10)
                    .Sort(sort =>
                    {
                        sort.Add(player => player.ParagonLevel).Descending();
                    });
            }))